/*
 * File: app/view/LoginPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.LoginPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginpanel',

    onSignIn: function(button, e, eOpts) {

        //var values = this.getLoginForm().getValues();
        var jsonPost = {};
        var username = 'ana';
        var password = 'ana';
        Ext.Ajax.request({
            url: 'http://localhost:8080/DogAdopter/rest/userservice/login/' +username + '/'+ password,
            method: 'GET',
            success: function(response) {
                var text = response.responseText;
                console.log(text);
                Ext.Viewport.setActiveItem('main-panel');

            },
            failure: function(response) {

                console.log(response.responseText);
            }
        });
    },

    onForgotPassword: function(button, e, eOpts) {
        Ext.Viewport.add({
            xtype: 'forgotpassword'
        });
    },

    onCreateAccount: function(button, e, eOpts) {
        Ext.Viewport.add({
            xtype: 'createaccount'
        });
    }

});